config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'

  get 'home/about', to: 'homes#about'
  resources :books, only: [:index, :show, :edit, :create, :destroy]
  resources :users, only: [:index, :show, :edit, :create]
  patch 'books/:id' => 'books#update', as: 'update_book'
  patch 'users/:id' => 'users#update', as: 'update_user'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

   belongs_to :user


  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 has_many :books, dependent: :destroy
has_one_attached :profile_image

 validates :name, uniqueness: true, length: { in: 2..20 }
 validates :introduction, length: {maximum: 50 }

def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

   def after_sign_out_path_for(resource)
    root_path
    end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController



  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    user = @book.user
    unless user.id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end


  def create
    @book = Book.new(book_params)
     @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
    else
    render :index
    end
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end



end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   before_action :is_matching_login_user, only: [:edit, :update]


  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
       redirect_to update_user_path
    else
       render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<br>
<h2>User info</h2>

<%= image_tag user.get_profile_image(100,100) %>

<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>

<div class="row">
<%= link_to edit_user_path(user), class: "btn btn-outline-secondary  btn-block " do %>
  <i class="fas fa-user-cog"></i>
<% end %>
</div>

<h2>New book</h2>

<%= form_with model: book do |f| %>

  <h6>Title</h6>
  <%= f.text_field :title,class:"form-control form-control-lg" %>

  <h6>Opinion</h6>
  <%= f.text_area :body,class:"form-control form-control-lg" %>

  <br>

  <%= f.submit 'Create Book' ,class: "btn btn-success" %>

<% end %>

app/views/books/edit.html.erb
<div ckass="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

    <br>
    <h1>Editing Book</h1>

    <% if @book.errors.any? %>
    <h2></h2><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>

    <%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

    <h6>Title</h6>
      <%= f.text_field :title,class:"form-control form-control-lg"%>
    <br>
    <h6>Opinion</h6>
      <%= f.text_area :body,class:"form-control form-control-lg" %>
    <br>
    <%= f.submit 'Update Book' ,class: "btn btn-success"%>
    <% end %>
    <br>
    <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
<%= @book.errors.count %>error prohibited this obj from being saved:

  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>

<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-3">

    <%= render 'books/list', book: @book, user: @user %>

    </div>

    <div class="col-md-8 offset-md-1">

    <br>
    <h2>Books</h2>

    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>

    <% @books.each do |book| %>

    <tbody>
      <tr>
        <td>
        <%= link_to user_path(book.user) do %>
        <%= image_tag book.user.get_profile_image(100,100) %>
        <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
      </tr>
    </tbody>
    <% end %>
    </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">

    <%= render 'books/list', book: @newbook,user: @user %>

    </div>

    <div class="col-md-8 offset-md-1">

      <br>
      <h2>Book detail</h2>

      <table class="table">
        <tr>
          <td>
            <%= link_to user_path(@user) do %>
            <%= image_tag @book.user.get_profile_image(100,100) %>
            <br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title,book_path(@book.id) %></td>
          <td><%= @book.body %></td>
            <% if @book.user == current_user %>
          <td><%= link_to "Edit",edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
          <td><%= link_to "Destroy",book_path(@book.id),method: :delete,"data-confirm" => "本当に消しますか？", class: "btn btn-sm btn-danger" %></td>
            <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<br>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      welcome to
      <i class="fas fa-book" aria-hidden="true"></i>
      <strong>Bookers</strong>
      !
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">

</div><div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">

<h1>welcome to <i class="fas fa-book" aria-hidden="true"></i>bookers!!</h1>
<h6>In <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers,</strong><br>
<br>
you can share and exchange your opinions , inpressions , and emotions<br>
<br>
about various books!</h6>
<br>

<div class="btn-wrapper col-10 mx-auto">

        <div class="row">
          <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block" %>
        </div>
        <br>
        <div class="row">
          <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
        </div>
      </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>


      <script src="https://kit.fontawesome.com/1a85cb0c49.js" crossorigin="anonymous"></script>
        <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="sticky-top">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">

        <div class="container">

          <a class="nav-bar-brand text-light" href="/">
            <span>Bookers</span>
          </a>

          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbarNavDropdown" style="">

          <ul class="navbar-nav ml-auto">

          <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to user_path(current_user), class:"nav-link text-light" do %>
              <i class="fas fa-home" aria-hidden="true"></i>Home
            <% end %>
          </li>

           <li class="nav-item">
            <%= link_to user_registration_path, class:"nav-link text-light" do %>
               <i class="fas fa-users" aria-hidden="true"></i>Users
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to books_path, class:"nav-link text-light" do %>
              <i class="fas fa-book-open" aria-hidden="true"></i>Books
            <% end %>
          </li>

           <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
              <i class="fas fa-sign-out-alt" aria-hidden="true"></i>Log out
            <% end %>
          </li>

          <% else %>

          <li class="nav-item">
            <%= link_to root_path, class:"nav-link text-light" do %>
              <i class="fas fa-home" aria-hidden="true"></i>Home
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to home_about_path, class:"nav-link text-light" do %>
              <i class="fas fa-link" aria-hidden="true"></i>About
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
              <i class="fas fa-user-plus" aria-hidden="true"></i>Sign up
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to new_user_session_path, class:"nav-link text-light" do %>
              <i class="fas fa-sign-in-alt" aria-hidden="true"></i>Log in
            <% end %>
          </li>

          <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

<main>
  <%= notice %>
  <%= yield %>
</main>
</body>

<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

    <br>
    <h2>User info</h2>

    <% if @user.errors.any? %>
    <h2><%= @user.errors.count %>error prohibited this obj from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>

    <%= form_with model: @user do |f| %>

    <h6>Name</h6>
      <%= f.text_field :name,class:"form-control form-control-lg" %>
    <br>
    <h6>Image</h6>
      <%= f.file_field :profile_image %>
    <br>
    <br>
    <h6>Introduction</h6>
      <%= f.text_field :introduction,class:"form-control form-control-lg" %>
    <br>
    <%= f.submit "Update User",class: "btn btn-secondary"%>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">

    <%= render 'books/list', book: @book, user: @user %>

    </div>

    <div class="col-md-8 offset-md-1">

      <h2>Users</h2>

        <table class="table">
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>

        <% @users.each do |user| %>

          <tr>
            <td>
              <%= image_tag user.get_profile_image(100,100) %>
            </td>
            <td><%= user.name %></td>
            <td><%= link_to "Show",user_path(user.id) %></td>
          </tr>

        <% end %>

        </table>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <%= render 'books/list', book: @book,user: @user %>
    </div>

    <div class="col-md-8 offset-md-1">



      <br>
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
              <%= image_tag @user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td><%= link_to book.title,book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>